package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseGoodstype;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Goodstype extends BaseGoodstype<Goodstype> {
	public static final Goodstype dao = new Goodstype().dao();
}
