package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseMaster;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Master extends BaseMaster<Master> {
	public static final Master dao = new Master().dao();
}
