package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseOrderform;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Orderform extends BaseOrderform<Orderform> {
	public static final Orderform dao = new Orderform().dao();
}
