package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BasePettype;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Pettype extends BasePettype<Pettype> {
	public static final Pettype dao = new Pettype().dao();
}
