package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BasePhase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Phase extends BasePhase<Phase> {
	public static final Phase dao = new Phase().dao();
}
