package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseSelection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Selection extends BaseSelection<Selection> {
	public static final Selection dao = new Selection().dao();
}
