package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseVip;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Vip extends BaseVip<Vip> {
	public static final Vip dao = new Vip().dao();
}
