package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStore<M extends BaseStore<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUserName(java.lang.String userName) {
		set("userName", userName);
		return (M)this;
	}
	
	public java.lang.String getUserName() {
		return getStr("userName");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public M setStoreName(java.lang.String storeName) {
		set("storeName", storeName);
		return (M)this;
	}
	
	public java.lang.String getStoreName() {
		return getStr("storeName");
	}

	public M setStoreAddress(java.lang.String storeAddress) {
		set("storeAddress", storeAddress);
		return (M)this;
	}
	
	public java.lang.String getStoreAddress() {
		return getStr("storeAddress");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public M setStoreStar(java.lang.Integer storeStar) {
		set("storeStar", storeStar);
		return (M)this;
	}
	
	public java.lang.Integer getStoreStar() {
		return getInt("storeStar");
	}

	public M setStoreType(java.lang.Integer storeType) {
		set("storeType", storeType);
		return (M)this;
	}
	
	public java.lang.Integer getStoreType() {
		return getInt("storeType");
	}

	public M setQq(java.lang.String qq) {
		set("qq", qq);
		return (M)this;
	}
	
	public java.lang.String getQq() {
		return getStr("qq");
	}

}
