package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGoodstype<M extends BaseGoodstype<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setGoodsTypeName(java.lang.String goodsTypeName) {
		set("goodsTypeName", goodsTypeName);
		return (M)this;
	}
	
	public java.lang.String getGoodsTypeName() {
		return getStr("goodsTypeName");
	}

}
