package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseArticle<M extends BaseArticle<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setArticleTitle(java.lang.String articleTitle) {
		set("articleTitle", articleTitle);
		return (M)this;
	}
	
	public java.lang.String getArticleTitle() {
		return getStr("articleTitle");
	}

	public M setArticleContent(java.lang.String articleContent) {
		set("articleContent", articleContent);
		return (M)this;
	}
	
	public java.lang.String getArticleContent() {
		return getStr("articleContent");
	}

	public M setStoreId(java.lang.Integer storeId) {
		set("storeId", storeId);
		return (M)this;
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("storeId");
	}

}
