package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMaster<M extends BaseMaster<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setPetName(java.lang.String petName) {
		set("petName", petName);
		return (M)this;
	}
	
	public java.lang.String getPetName() {
		return getStr("petName");
	}

	public M setPetKind(java.lang.String petKind) {
		set("petKind", petKind);
		return (M)this;
	}
	
	public java.lang.String getPetKind() {
		return getStr("petKind");
	}

	public M setPetAge(java.lang.Integer petAge) {
		set("petAge", petAge);
		return (M)this;
	}
	
	public java.lang.Integer getPetAge() {
		return getInt("petAge");
	}

	public M setPetType(java.lang.String petType) {
		set("petType", petType);
		return (M)this;
	}
	
	public java.lang.String getPetType() {
		return getStr("petType");
	}

	public M setPetImg(java.lang.String petImg) {
		set("petImg", petImg);
		return (M)this;
	}
	
	public java.lang.String getPetImg() {
		return getStr("petImg");
	}

	public M setMasterName(java.lang.String masterName) {
		set("masterName", masterName);
		return (M)this;
	}
	
	public java.lang.String getMasterName() {
		return getStr("masterName");
	}

	public M setMasterAddress(java.lang.String masterAddress) {
		set("masterAddress", masterAddress);
		return (M)this;
	}
	
	public java.lang.String getMasterAddress() {
		return getStr("masterAddress");
	}

	public M setMasterPhone(java.lang.String masterPhone) {
		set("masterPhone", masterPhone);
		return (M)this;
	}
	
	public java.lang.String getMasterPhone() {
		return getStr("masterPhone");
	}

	public M setUserName(java.lang.String userName) {
		set("userName", userName);
		return (M)this;
	}
	
	public java.lang.String getUserName() {
		return getStr("userName");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public M setVipId(java.lang.Integer vipId) {
		set("vipId", vipId);
		return (M)this;
	}
	
	public java.lang.Integer getVipId() {
		return getInt("vipId");
	}

}
