package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePhase<M extends BasePhase<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setIsEnd(java.lang.Integer isEnd) {
		set("isEnd", isEnd);
		return (M)this;
	}
	
	public java.lang.Integer getIsEnd() {
		return getInt("isEnd");
	}

	public M setPhaseNum(java.lang.Integer phaseNum) {
		set("phaseNum", phaseNum);
		return (M)this;
	}
	
	public java.lang.Integer getPhaseNum() {
		return getInt("phaseNum");
	}

	public M setStoreId(java.lang.Integer storeId) {
		set("storeId", storeId);
		return (M)this;
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("storeId");
	}

}
