package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrderform<M extends BaseOrderform<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setServiceId(java.lang.Integer serviceId) {
		set("serviceId", serviceId);
		return (M)this;
	}
	
	public java.lang.Integer getServiceId() {
		return getInt("serviceId");
	}

	public M setStoreId(java.lang.Integer storeId) {
		set("storeId", storeId);
		return (M)this;
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("storeId");
	}

	public M setIsAccept(java.lang.Integer isAccept) {
		set("isAccept", isAccept);
		return (M)this;
	}
	
	public java.lang.Integer getIsAccept() {
		return getInt("isAccept");
	}

	public M setMasterId(java.lang.Integer masterId) {
		set("masterId", masterId);
		return (M)this;
	}
	
	public java.lang.Integer getMasterId() {
		return getInt("masterId");
	}

	public M setGoodsId(java.lang.Integer goodsId) {
		set("goodsId", goodsId);
		return (M)this;
	}
	
	public java.lang.Integer getGoodsId() {
		return getInt("goodsId");
	}

	public M setOrderType(java.lang.Integer orderType) {
		set("orderType", orderType);
		return (M)this;
	}
	
	public java.lang.Integer getOrderType() {
		return getInt("orderType");
	}

}
