package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSelection<M extends BaseSelection<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setPetName(java.lang.String petName) {
		set("petName", petName);
		return (M)this;
	}
	
	public java.lang.String getPetName() {
		return getStr("petName");
	}

	public M setPetImg(java.lang.String petImg) {
		set("petImg", petImg);
		return (M)this;
	}
	
	public java.lang.String getPetImg() {
		return getStr("petImg");
	}

	public M setPetStar(java.lang.Integer petStar) {
		set("petStar", petStar);
		return (M)this;
	}
	
	public java.lang.Integer getPetStar() {
		return getInt("petStar");
	}

	public M setSelectionTime(java.lang.Integer selectionTime) {
		set("selectionTime", selectionTime);
		return (M)this;
	}
	
	public java.lang.Integer getSelectionTime() {
		return getInt("selectionTime");
	}

	public M setStoreId(java.lang.Integer storeId) {
		set("storeId", storeId);
		return (M)this;
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("storeId");
	}

}
